# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
variables:
- group: AzureMLConfig
- name  : 'test'
  value : '.ci/run_pytest.py'
- name  : 'maxnodes'
  value : 4
- name  : 'clustername'
  value : 'cv-nightly-gpu'
- name  : 'vmsize'
  value : 'STANDARD_NC6'
- name  : 'dockerproc'
  value : 'gpu'
- name  : 'condafile'
  value : 'environment.yml'
- name  : 'rg'
  value : 'cvbp_project_resources'
- name  : 'wsname'
  value : 'cvws'
trigger: none

pr: none
#- staging 
#- master
  
pool:
 vmImage: 'ubuntu-16.04'

jobs:
- job: Smoke
  displayName : 'Smoke: no CV tests yet'

variables:
  - name  : 'testfolder'
    value : 'tests/integration'
  - name  : 'junitxml'
    value : 'reports/test-smoke.xml'
  - name  : 'testmarkers'
    value : '"not notebooks and not spark and not gpu"'
  - name  : 'expname'
    value : 'nightly-smoke-test-linux-gpu'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
    addToPath: true
  displayName: 'Use Python 3.6'

- job : Integration
  displayName : 'Integration'

  variables:
  - name  : 'testfolder'
    value : 'tests/integration'
  - name  : 'junitxml'
    value : 'reports/test-int.xml'
  - name  : 'testmarkers'
    value : '"not notebooks and not spark and not gpu"'
  - name  : 'expname'
    value : 'nightly-int-test-linux-gpu'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
      addToPath: true
    displayName: 'Use Python 3.6'

- script:
    az login --service-principal -u $(spidentity) -p $(spsecret) --tenant $(sptenant)
  displayName: 'Login to Azure'

- script:
    # bug fix for azureml sdk 7/18/2019
    pip install paramiko==2.4.2;
    pip install --upgrade azureml-sdk;
    pip install azure-cli;
    python .ci/submit_azureml_pytest.py --subid $(subscriptionid) --test $(test) --testfolder $(testfolder) --condafile $(condafile) --testmarkers $(testmarkers) --clustername $(clustername) --expname $(expname) --dockerproc $(dockerproc) --junitxml $(junitxml) --reponame $(Build.Repository.Name) --branch $(Build.SourceBranchName) --rg $(rg) --wsname $(wsname)
  displayName: 'submit_azureml_pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-*.xml'
  condition: always()
  inputs:
    testResultsFiles: '**/test-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Test results for CV AzureML PyTest'